name: functions
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - jupyter
  - notebook
  - ipykernel
  - pip
  - pip:
    - gpxpy>=1.5.0
    - rich>=12.0.0